### ISSUE TITLE
Original source

### ISSUE THREAD

**Issue by FLYBYME** [OpenSolo/artoo#1]
Who was this released to? Did 3DR give up the code or was to gained some other way? If so how?

**Comment by davidbuzz** [comment]
read this: https://github.com/OpenSolo/artoo/blob/master/SOURCE

**Comment by FLYBYME** [comment]
I already google searches the file name and nothing showed up. Did they send you the files directly or is it hosted somewhere?

**Comment by davidbuzz** [comment]
3DR approached the ArduPilot team directly on this matter and released the files directly to us. What you see in the first commit/s of each of these repo/s is exactly what 3DR sent us.
