### ISSUE TITLE
Opensolo not compatible with Solo Simulator

### ISSUE THREAD

**Issue by lordneeko** [OpenSolo/artoo#10]
So I know this may be considered low priority, but it's high priority for my son.  The solo simulator has no problem recognizing when my open solo artoo connects, and the on screen display of the sticks moving works fine. But it doesn't recognize any button presses, specifically the FLY button, so you cannot take off.

It worked just fine before I updated to open solo3.0.0.

I'd love to see if you could look into why it doesn't work anymore. I might be able to contribute some code help, but my c isn't strong. I can test it though!!  My son sure would appreciate it.

Thanks
Play store link
https://play.google.com/store/apps/details?id=com.o3dr.solosimulator

**Comment by Pedals2Paddles** [comment]
The simulator app will not work with Open Solo.  Since 3DR has not released that app to the open source community, it cannot be updated to keep up with the changes in Open Solo.  There is nothing we can do about it.

**Comment by lordneeko** [comment]
I know there was a source saying they were still "thinking" about open sourcing the solo app (which would put Solex out of business..sort of) but what came of those discussions? And I wonder if they'd be willing to OS the simulator.  Again, I know it is very low priority. 

Probing question, is there a way that the Artoo can know whether it is connected to the actual Solo or the simulator? It appears that the changes made [here](https://github.com/OpenSolo/artoo/commit/4d77671f3de14059ae9f01b52dc8843d98b6a2f5) are the changes which "broke" compatibility.  But, if the artoo can know it is connected to the simulator, could it revert to the "old" button functionality?

Perhaps i'm simplifying it way too much..and I totally understand that probably no one but me cares.  I would like to find a way to practice (rehearse) the modes prior to going on site.  

Thanks for responding.

**Comment by Pedals2Paddles** [comment]
Yes, that button reworking is why the simulator app no longer works.  No, it is not able to know what app is connected.  Even if it was, it would not be practical to reengineer for compatibility with the old stuff.

The simulator app has seen no development for nearly 3 years. There has been no movement on open sourcing it or the 3DR Solo app. I'm sorry to say, it is dead. Even if they magically open sourced it today, there is nobody that even has the desire to work on it. It's dead and has been for a long time now.

**Comment by lordneeko** [comment]
Ok thanks!
Looking forward to the inevitable future awesome of Open Solo. Thanks for
the work you've put into this.
