### ISSUE TITLE
Warning - current status

### ISSUE THREAD

**Issue by BrettRyland** [OpenSolo/artoo#11]
Looking at the history of ReadMe.md, the "WORK IN PROGRESS" warning has existed since the initial commit, however, version 3.0.0 was released earlier this year and the version number would indicate some stability. Can someone comment on the current validity of the warning, specifically the "This code is known to be broken and/or incomplete. IT DOES NOT WORK." part? Thanks!

**Comment by davidbuzz** [comment]
the other repo/s had their readme's updated some time ago.  I've just
fixed this repo to match the text in the others.
https://github.com/OpenSolo/artoo/commit/bd20185cb66ec78d0d80a78bcb02635b3c65347e
