### ISSUE TITLE
Feature Request: Single Controller for multiple Solos

### ISSUE THREAD

**Issue by geekness** [OpenSolo/artoo#2]
I think being able to have a number of Solos bound to a single controller would be a great benefit.
This request isn't to be able to fly multiple Solos at the same time, just have a number of solos bound to a single controller.
The controller would then have different settings for the controls/buttons dependent on which Solo is being flown.

Apologies if this is the wrong location for this request.

**Comment by proficnc** [comment]
Yeah, this would be really handy for swarming or many other things, as well as for what you are asking for..

this would require some scripting to work, We would love to see an attempt made, are you able to try?

**Comment by davidbuzz** [comment]
I'm sure this would be possible, yes.  “Pull Requests Welcome”.    In the mean time, I don't think this issue need to stay open, so I'm going to close it now, thanks.!
