### ISSUE TITLE
Add SBUS support for controls

### ISSUE THREAD

**Issue by ghost** [OpenSolo/artoo#4]
Hi,

In order to use the sololink with a wider variety of boards, I think it would be cool to have the possibility to output the rc channels through SBus instead of DSM.

Obviously that would require an external inverter...

If someone has the skills/wants to do that... I'd be willing to pay for that feature if necessary.

thank you

**Comment by FLYBYME** [comment]
As far as I can tell the DSM is the only thing holding back sololink (NOT artoo) from been a general purpose control link. I am currently building from source but the plan is to implement some sort of toggle to change from DSM to PPM to maybe SBus. PPM is something I will  implement first. The easy way around this would be to use an arduino to convert DSM to SBus. Take a look: https://github.com/simondlevy/SpektrumDSM

**Comment by davidbuzz** [comment]
this is not the place for feature-requests, this is for bugs/faults/errors.
